name: CI-test

env:
  GITHUB_ACTIONS: true

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  workflow_dispatch:

jobs:
  CI:
    strategy:
      matrix:
        os-version: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        poetry-version: ["1.8.3"]

    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Setup vapoursynth
        uses: deadnews/action-setup-vs@v1.1.0

      - name: Test
        run: |
          poetry install

          make lint
          make test
